name: Workflow Keepalive
description: >-
  GitHub Action to prevent GitHub from disabling scheduled workflows due to
  repository inactivity
branding:
  icon: activity
  color: red
inputs:
  GITHUB_TOKEN:
    required: false
    description: >-
      GITHUB_TOKEN with actions: write permissions
      (default: github.token)
runs:
  using: composite
  steps:
    - name: Re-enable workflow
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN || github.token }}
      shell: sh
      run: |
        case "${GITHUB_WORKFLOW_REF:?}" in
          "${GITHUB_REPOSITORY:?}"/.github/workflows/*.y*ml@*) ;;
          *) false ;;
        esac
        workflow="${GITHUB_WORKFLOW_REF%%@*}"
        workflow="${workflow#${GITHUB_REPOSITORY}/.github/workflows/}"
        gh api -X PUT "repos/${GITHUB_REPOSITORY}/actions/workflows/${workflow}/enable"
