name: Geohashing
on:
  schedule:
    - cron: '0 15 * * *' # Run the script daily, after the New York stock exchange opens
  workflow_dispatch:

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - run: pip install -r requirements.txt
    - run: python -u main.py
      timeout-minutes: 10
      env:
        WIKI_USERNAME: ${{ secrets.WIKI_USERNAME }}
        WIKI_PASSWORD: ${{ secrets.WIKI_PASSWORD }}
