name: Geohashing
on:
  schedule:
    - cron: '30 13 * * *' # Run the script daily, when the NYSE opens (9:30 EDT). This will be 1h early under standard time, but whatever.
  workflow_dispatch:

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install -r requirements.txt
    - run: python -u main.py
      timeout-minutes: 10
      env:
        WIKI_USERNAME: ${{ secrets.WIKI_USERNAME }}
        WIKI_PASSWORD: ${{ secrets.WIKI_PASSWORD }}
